#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

define("CREATIONS_PATH", __DIR__."/database/creations");
define("MIGRATIONS_PATH", __DIR__."/database/migrations");
define("SEEDS_PATH", __DIR__."/database/seeds");

/**
 * Script for creating, destroying, and seeding the app's database
 */
class Novice {

    function __construct($args)
    {
        $this->args = $args;
    }

    function help()
    {
        echo "usage: php " . $this->args[0] . " [create|migrate|seed]\n";
    }

    function exec()
    {
        if (count($this->args) <= 1) {
            $this->help();
        } else {
            switch ($this->args[1]) {
                case "create":
                    $this->runCreations();
                    break;

                case "migrate":
                    $this->runMigrations();
                    break;

                case "seed":
                    $this->runSeed();
                    break;

                case "help":
                case "--help":
                default:
                    $this->help();
                    break;
            }
        }
    }

    function runCreations()
    {
        $files = glob(CREATIONS_PATH.'/*.php');

        $this->run($files);
    }


    function runMigrations()
    {
        $files = glob(MIGRATIONS_PATH.'/*.php');

        $this->run($files);
    }

    function runSeed()
    {
        $files = glob(SEEDS_PATH.'/*.php');

        $this->run($files);
    }
    
    private function run($files)
    {
        foreach ($files as $file) {
            require_once($file);

            $class = basename($file, '.php');

            $obj = new $class;
            $obj->run();
        }
    }
}

$novice = new Novice($argv);
$novice->exec();
